### ISSUE TITLE
Поздрави!

### ISSUE THREAD

**Issue by bg3dh4jh6m** [Kostadin/Places-in-Bulgaria#1]
Здравейте,
Бях започнал да си сглобявам същия JSON от публичните извори и открих Вашият.
За момента правя любителски проект и не знам дали ще стане нещо комерсиално.
Можете ли да потвърдите че нямате нищо напротив да използвам този файл?

Благодарности,
Ник

**Comment by Kostadin** [comment]
Всички данни тук са публични. Може да ги използвате както ви е нужно. Надявам се да ви помогнат.

Успех!
